### ISSUE TITLE
invalid grant

### ISSUE THREAD

**Issue by ndk-sm** [webparking/laravel-visma#15]
Why is fetching the access token responding with invalid grant?

**Comment by remkobrenters** [comment]
My gut feeling is it has something to do with the scope (see config file) that is not correct for your user / setup. Cannot verify this as I do not have any active projects or licenses using Visma. If there is something in the package that requires an update for newer versions of Visma please submit a PR.

**Comment by ndk-sm** [comment]
> 

never mind, I had just made a mistake
