### ISSUE TITLE
[Question] Have anyone managed to make a POST request?

### ISSUE THREAD

**Issue by nivv** [webparking/laravel-visma#3]
I'm struggling with the next to useless documentation that Visma puts out here: https://eaccountingapi-sandbox.test.vismaonline.com/swagger/ui/index#!/CustomerInvoicesV2/CustomerInvoicesV2_Post

I'm not sure what I'm doing wrong, but the response I get when doing a POST request is this:

```json
{
"ErrorCode": 6001,
"DeveloperErrorMessage": "Exception - Unsupported Media Type",
"ErrorId": "080e40a9-93cb-43c3-ae2e-5c804be969ff",
"Errors": null
}
```

Have you managed to get a POST request working? If so, can you please share your entity?

**Comment by remkobrenters** [comment]
I think the `errorMessage` could be confusing as this code indicates an issue with a date format (property or filter). If you get this working I would appreciate a PR for required updates / additions to the `baseEntity` for POST requests (we did not need them so did not implemented them).

**Comment by lagerroos** [comment]
I actually added this to BaseEntitiy just two days ago. Let me wrap it up
to a PR instead. Give me an hour or two 😄

Den sön 29 nov. 2020 11:30Remko Brenters <notifications@github.com> skrev:

**Comment by lagerroos** [comment]
In the meantime, Albin go check my fork altitudeevents/laravel-visma

Den sön 29 nov. 2020 11:34Tommie Lagerroos <tommie@lagerroos.nu> skrev:

**Comment by remkobrenters** [comment]
@lagerroos cool. See you made some nice improvements, would be awesome if you can create a PR to make this wrapper a bit less 'bare minimal'.

**Comment by nivv** [comment]
@lagerroos I've tried your branch, and I managed to create orders and invoices. But god damn, I would be a happy camper if Visma bothered to specify which parameters are mandatory. Anyways I managed to create an invoice with the below payload:

```php
        $object = [
            "customerid" => "1cd72a91-07a3-49f9-b16b-3a3579ac4f0a",
            "paymentdate" => now()->todatestring(),
            "euthirdparty" => true,
            "rotreducedinvoicingtype" => 0,
            "orderdate" => now()->todatestring(),
            // "shippeddatetime" => now()->todatetimestring(),
            "deliveredamount" => 150,
            "shippeddatetime" => now()->todatestring(),
            "status" => 3,
            "currencycode" => "sek",
            "amount" => 350,
            "reversechargeonconstructionservices" => false,
            "rows" => [
                [
                    "linenumber" => 1,
                    "deliveredquantity" => 350,
                    "istextrow" => false,
                    "articleid" => "d7456f7d-d480-4651-81e5-d956440d89f3",
                    "articlenumber" => "ff01",
                    "text" => "försäljning livsmedel",
                    "quantity" => 350,
                    "unitprice" => 1,
                    "isworkcost" => false,
                    "eligibleforreversechargeonvat" => false,
                    "amount" => 350
                ],
            ]
        ];
```
