### ISSUE TITLE
Autoloading fails

### ISSUE THREAD

**Issue by dbijman** [webparking/laravel-visma#9]
When adding the Laravel-visma requirement with composer, it generates an error for the autoloading:
Generating optimized autoload files
Class App\Http\Controllers\Controller located in ./app/Http/Controllers/Controller copy.php does not comply with psr-4 autoloading standard. Skipping.
Class App\Helpers\Helper located in ./app/Helpers/helpers.php does not comply with psr-4 autoloading standard. Skipping.

I'm kinda new to using Laravel so maybe I'm doing something wrong, any ideas?

**Comment by dbijman** [comment]
Seems to be an issue in my project, never mind :)

**Comment by remkobrenters** [comment]
Self resolving issues, those are the best. Have a nice day.
